### ISSUE TITLE
Text and icons go dark after applying a GDM picture.

### ISSUE THREAD

**Issue by in4matix** [imarkoff/Marble-shell-theme#10]
As described above. Tried fixing by re-installing the shell theme, but issue is persistent.

**Comment by imarkoff** [comment]
Is this issue only happening in gdm or during an active session? If during an active session, does this problem also occur with other themes or with the default theme?

**Comment by in4matix** [comment]
Worked fine before applying GDM picture. Ever since applying the GDM picture, it is persistent after restarts during active sessions. It is doing it for all tar downloaded variants. On mouse-over, the text lights up.

**Comment by in4matix** [comment]
I am using this script [https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background](url)

**Comment by imarkoff** [comment]
Thank you for reporting this issue, I will try to replicate the bug in the coming days to see if it is really on the theme side

**Comment by imarkoff** [comment]
Can you provide which version of Ubuntu you are using and what commands you used to set the background?

**Comment by in4matix** [comment]
Ubuntu 22.3.04 Gnome 42.9. Running the script: 
`sudo ./ubuntu-gdm-set-background --image /home/daniel/Store/GdmScript/GdmWP/gdm-12.jpg`

**Comment by imarkoff** [comment]
Did you apply theme as desribed below or use another way?
> ** Manual installation **
> 1. Go to the Files section
> 2. Download Marble-shell-theme.tar.xz
> 3. Unpack it to the ~/.themes folder
> 4. Open GNOME Tweaks, go to Appearance - Themes - Shell.
> 5. Select the shell theme you want.

btw, I tried to recreate the bug on Ubuntu 22.04.3, but did not see it. :(
![Screenshot from 2023-11-12 10-37-58](https://github.com/imarkoff/Marble-shell-theme/assets/81307050/0eb63cd0-17c1-4f4d-a08a-a4e5e4e755e7)
![Screenshot from 2023-11-12 10-38-24](https://github.com/imarkoff/Marble-shell-theme/assets/81307050/9c47edd3-1ae7-4083-8396-2626e4218606)

**Comment by imarkoff** [comment]
Can you provide me with screenshots that show the bug?

**Comment by in4matix** [comment]
Yes, that is the exact installation procedure I used.
[Screencast from 12-11-2023 11:15:51.webm](https://github.com/imarkoff/Marble-shell-theme/assets/62904593/322a0ed8-9144-4f90-b05c-5a0ab548a954)

**Comment by imarkoff** [comment]
What extensions you have installed and enabled?

**Comment by in4matix** [comment]
I have many, but that should not affect the theme, right? I am currently using WhiteSur dark theme and it works fine with the GDM script. Your theme worked perfectly fine until I ran the script to change my login picture, and only after doing that the text in the shell menus went dark.

**Comment by imarkoff** [comment]
I still managed to repeat this bug.
![image](https://github.com/imarkoff/Marble-shell-theme/assets/81307050/60bebd85-edc5-4f53-a53c-8c0f02a1ddae)

> Your theme worked perfectly fine until I ran the script to change my login picture, and only after doing that the text in the shell menus went dark.

It is not script problem.

This issue arose because the WhiteSur theme was applied globally (the styles were built directly into the GNOME Shell), and the Marble theme was applied on top of it.

The problem is that this theme has a lot of styles marked with `!important`. The Marble theme has the corresponding styles, but without the `!important` marking (because there is no need for Adwaita (GNOME) or Yaru (Ubuntu) themes). 

Because of this, in some places WhiteSur styles have a higher priority than styles from the Marble theme, and therefore some Marble styles cannot overlay WhiteSur styles, and that is why this problem arises. 

So, if you wanna use my theme, open your terminal, go to WhiteSur-gtk-theme folder, run the command below and log out:
```bash
sudo ./tweaks.sh -g -r
```
And this issue will disappear.

**Comment by in4matix** [comment]
You are brilliant!! Thank you so so very much!! I should have mentioned that I applied the WhiteSur GDM tweak initially, but the background was too blurred and I just wanted a picture for the login background. Once again, brilliant, thank you!!

**Comment by in4matix** [comment]
Marble shell theme is by far the best shell theme available, trust me, I have tried them all.

**Comment by imarkoff** [comment]
@in4matix, thank you so muuuuuuuuch 🥹🤗

**Comment by in4matix** [comment]
Sorry to be a pain, is there a way to adjust opacity? Just need a bit more opacity then it is perfect.

**Comment by imarkoff** [comment]
Where you want to change opacity?

**Comment by in4matix** [comment]
The opacity of the drop-down menus

**Comment by imarkoff** [comment]
1. Open the terminal.

2. Clone the git repository and change the directory:
```bash
git clone https://github.com/imarkoff/Marble-shell-theme.git
cd Marble-shell-theme
```

3. Open `colors.json` and find `BACKGROUND-COLOR`. `'a'` responses for the transparency, so change its value as you wish.

4. Run the program (install all accent colors, light & dark mode):
```bash
python install.py -a
```
   more vibrant color in active buttons:
   ```bash
   python install.py -a --filled
   ```
5. After successful file creation open GNOME Tweaks, go to `Appearance - Themes - Shell`.
Select the shell theme you want.

**Comment by in4matix** [comment]
I think I love you. Thank you!!!

![Screenshot from 2023-11-12 22-28-46](https://github.com/imarkoff/Marble-shell-theme/assets/62904593/d8526525-6070-48a5-a560-ebd1d9a2a4bd)
