### ISSUE TITLE
Adjusting text brightness

### ISSUE THREAD

**Issue by in4matix** [imarkoff/Marble-shell-theme#15]
Hey,
Just wondering if there might be a way to tone down the brightness of text while the theme is installed, or would I have to re-install?

**Comment by imarkoff** [comment]
You can edit css in `~/.themes/Marble-...-...` but it will take too much time.

However,  you can change text color in `colors.json` here: https://github.com/imarkoff/Marble-shell-theme/blob/70694411b8b576490fd936d6cc0720a605264361/colors.json#L305-L349

and reinstall the theme.

`s` - saturation
`l` - lightness
`a` - transparency (alpha)

Sorry for replying after a week. Maybe I'll add the ability to change text color using the script later.

**Comment by in4matix** [comment]
Okay... I'm not really sure what values to change to make the text less bright white to something that is a bit easier on the eyes. Basically I want to go from this:
![Screenshot from 2024-02-04 23-05-00](https://github.com/imarkoff/Marble-shell-theme/assets/62904593/ab409675-314b-4d94-8875-fa0cf010b198)
To this (The "No Notifications" color) like a light grey...
![Screenshot from 2024-02-04 23-05-39](https://github.com/imarkoff/Marble-shell-theme/assets/62904593/4f3b8ad2-d2b5-4880-b38c-5c937c0cb6a0)

**Comment by imarkoff** [comment]
I gotchu. Update both the `light` and `dark` sections of the `TEXT-PRIMARY-COLOR` value with the new `a` value of 0.38.

It should go from this
```json
        "TEXT-PRIMARY-COLOR" : {
            "_comment" : "Used as primary color in text",

            "light" : {
                "s" : 71,
                "l" : 10,
                "a" : 0.87
            },

            "dark" : {
                "s" : 65,
                "l" : 95,
                "a" : 1
            }
        },
```

to this
```json
        "TEXT-PRIMARY-COLOR" : {
            "_comment" : "Used as primary color in text",

            "light" : {
                "s" : 71,
                "l" : 10,
                "a" : 0.38
            },

            "dark" : {
                "s" : 65,
                "l" : 95,
                "a" : 0.38
            }
        },
```

**Comment by in4matix** [comment]
0.58 is the magical value for me. Thank you! You rock dude. Love you brother. 
P.s. Do you accept donations? If so, please send link.
