### ISSUE TITLE
Gtk4 app supports

### ISSUE THREAD

**Issue by stoneC0der** [imarkoff/Marble-shell-theme#17]
Hey there! nice theme.
I have been adding more themes to gnome, so 
- WhiteSur
- Orchis
and now this one, but I wondering if this theme has support for gtk4 (libadwaita) apps.
If yes, how to install it

I took a look a the one of the above theme installation for libadwaita & flatpak, probably can get my hands dirty, I don't enough free time for now.

**Comment by imarkoff** [comment]
Thanks. 
Marble theme does not currently provide theming for libadwaita apps. I've worked on this before, but abandoned it due to strong similarities with the standard theme. Unfortunately, GTK 3/4 will not be supported in the near future.
