### ISSUE TITLE
Theme breaks on GNOME 46

### ISSUE THREAD

**Issue by KoNickss** [imarkoff/Marble-shell-theme#18]
**Describe the bug**
Theme makes every UI element on shell look selected on gnome 46

**To Reproduce**
Install gnome 46

**Expected behavior**
Have the theme look ok

**Screenshots**
![Screenshot from 2024-03-24 19-51-56](https://github.com/imarkoff/Marble-shell-theme/assets/61112636/596690d7-9e67-4fd6-b7f4-b8db8657ebd5)
![Screenshot from 2024-03-24 19-52-06](https://github.com/imarkoff/Marble-shell-theme/assets/61112636/3e74da90-472b-4251-950c-7347913e219c)

**Comment by Sherlock-Holo** [comment]
also the calendar is broken
![image](https://github.com/imarkoff/Marble-shell-theme/assets/10096425/47958212-f625-40e5-bbbb-0ae154388f21)

**Comment by imarkoff** [comment]
Enjoy :)

![Screenshot from 2024-03-25 13-15-49](https://github.com/imarkoff/Marble-shell-theme/assets/81307050/90c6ec3b-037e-406b-8d88-6884ebe977dd)

**Comment by KoNickss** [comment]
thank you so much <3333 best shell theme on gnome
