### ISSUE TITLE
Search entry is too dark (ArcMenu)

### ISSUE THREAD

**Issue by in4matix** [imarkoff/Marble-shell-theme#20]
Sorry to bug you for another trivial personal snag that is not an issue... Just want to ask if it is possible to achieve below:

The color on mouse hover (marked with green) is a bit too dark. Can it match the color marked with red?

![Screenshot from 2024-03-30 10-00-56](https://github.com/imarkoff/Marble-shell-theme/assets/62904593/f5d37a33-561c-4625-a10d-8230286c59b3)

So, basically... Not sure if I am making sense...

 
![Screenshot from 2024-03-30 10-01-02](https://github.com/imarkoff/Marble-shell-theme/assets/62904593/c1be8e00-3f9c-4b7c-bb78-d1962ed1454e)

**Comment by imarkoff** [comment]
Done
![Screenshot from 2024-04-01 13-18-56](https://github.com/imarkoff/Marble-shell-theme/assets/81307050/5a15be05-a520-40ca-aaa2-a08e3e0bc6be)
![Screenshot from 2024-04-01 13-19-04](https://github.com/imarkoff/Marble-shell-theme/assets/81307050/4b81b910-a3d3-4e0d-87ba-a6d1d77b17e6)

**Comment by in4matix** [comment]
Hi, Pardon my ignorance, but how do I go about applying this?

**Comment by imarkoff** [comment]
> Hi, Pardon my ignorance, but how do I go about applying this?

If you installed this theme using the installation script before, do this:
open Marble folder in console,
```
git pull
python install.py -a --filled
```


But if you have already changed the css styles directly, add these lines to the end of the file
```css
StEntry {
     background-color: rgba(180, 216, 253, 0.08);
}

.search-entry {
     background-color: rgba(28, 30, 32, 0.9);
}
```

**Comment by in4matix** [comment]
Sorry to waste your time. So either way, I will have to re-install the theme right? Also, it is not just ArcMenu, but notifications as well:
![Screenshot from 2024-04-01 19-39-21](https://github.com/imarkoff/Marble-shell-theme/assets/62904593/7851410a-1491-4d46-bd2e-215e57a97445)

**Comment by in4matix** [comment]
Not sure if you will recall, but you helped me last year some time to override the transparency of the theme, so my menus are a bit more transparent than normal. But, I was referring to the dark color of the notification that is similar to the dark color of the ArMenu search box.

**Comment by imarkoff** [comment]
Fixed but i dunno if it'll look good with your transparency in menus.

![Screenshot from 2024-04-02 21-18-37](https://github.com/imarkoff/Marble-shell-theme/assets/81307050/d544cd17-89f6-4055-b4c0-d6edf402d4b1)

How to pull changes:
```
git stash
git pull
git stash pop
```

**Comment by in4matix** [comment]
Thank you. I will give it a try in the next couple of days and give you feedback.

**Comment by in4matix** [comment]
Hi! I finally mustered up the courage an attempted it. I managed to also implement the text color change! I used 0.58 and a lot better on the eyes now. ArcMenu looks great now, but notifications is a bit too light now (probably because I am using the more transparent menu setting as you said/). It looks good on mouse hover, but without mouse hover it is just too light now (sorry for being such a pain)

Without mouse hover:
![Screenshot from 2024-04-03 17-29-03](https://github.com/imarkoff/Marble-shell-theme/assets/62904593/aa5f79a1-64fc-4723-9c6d-90f3cf7792a1)

With mouse hover:
![Screenshot from 2024-04-03 17-29-19](https://github.com/imarkoff/Marble-shell-theme/assets/62904593/1325deae-426e-447a-8ea9-57b9b02b41e2)

I tried to figure it out, but I'm too stupid and don't want to break things.

ArcMenu:
![Screenshot from 2024-04-03 17-30-15](https://github.com/imarkoff/Marble-shell-theme/assets/62904593/3c473198-9acf-406c-a221-839f55762a07)

![Screenshot from 2024-04-03 17-30-27](https://github.com/imarkoff/Marble-shell-theme/assets/62904593/68a2300e-7da3-4dcf-a660-85220750beb8)

**Comment by in4matix** [comment]
After checking it out some more, it really depends on the wallpaper. My collection of wallpapers are classy light colorful and textured wallpapers. I had a couple of darker ones which I have deleted. So, I am very happy with the way it is now. Thanks a ton Bro. Much Love.
