### ISSUE TITLE
Theme not applying to panel menu

### ISSUE THREAD

**Issue by Eiley2** [imarkoff/Marble-shell-theme#22]
**Describe the bug**
I'm trying to install the theme, but the panel menu isn't changing. I've tried rebooting, reinstalling gnome-shell but nothing works.

**Screenshots**

![image](https://github.com/imarkoff/Marble-shell-theme/assets/84003742/2766c6a0-7cab-4961-bb71-b636f0a9e15b)

**Additional context**
This is my system info

![image](https://github.com/imarkoff/Marble-shell-theme/assets/84003742/792e8720-b639-42d8-a3e8-bff0acfe2354)

If I'm not doing something right, I would like some guidence if is possible. Thanks in advance!

**Comment by Eiley2** [comment]
i installed the last version of ubuntu and it worked!

**Comment by in4matix** [comment]
I honestly don't get why people would go from an LTS just to get the latest....? Gnome 46 is riddled with issues. I have Gnome 46 running in a virtual environment and I just don't see any advantage of upgrading. Big difference between cutting edge and bleeding edge. Marble shell works perfectly on Ubuntu 22.04 LTS Wayland. With my free Pro subscription I am covered right up to 2034. So even when Ubuntu 24 LTS is released, I will probably wait a year or two for them to get it to a stable state. Most corporate clients are still on Ubuntu 20 LTS....

**Comment by in4matix** [comment]
I am sure I have the perfect setup (Well according to my taste). Marble shell theme, WhiteSur GTK Theme, My own Icon Theme...

![Screenshot from 2024-04-05 08-19-23](https://github.com/imarkoff/Marble-shell-theme/assets/62904593/323cc886-f4e9-4752-aad4-ea250ed4542e)

![Screenshot from 2024-04-05 08-19-45](https://github.com/imarkoff/Marble-shell-theme/assets/62904593/a7bd8571-bd9c-489e-85ce-bfc81c571f71)

I have over 50 extensions that work together flawlessly. Boots up in about 5 seconds, blazingly fast, stable and secure.
