### ISSUE TITLE
Touch keyboard background is missing/transparent

### ISSUE THREAD

**Issue by Excigma** [imarkoff/Marble-shell-theme#25]
**Describe the bug**
Touch keyboard buttons and background is missing/transparent

**To Reproduce**
1. Open the touch keyboard, you can do this by swiping up from the bottom edge when a flip laptop is flipped around

**Expected behavior**
Keyboard should have a background

**Screenshots**
![image](https://github.com/imarkoff/Marble-shell-theme/assets/30280397/98c05261-d195-4475-b926-ef65185e7d72)
light terminal jumpscare

Let me know if there is any way I can help - I'm not too sure if there is something like browser devtools that I could bring up to help debug/fix this? I understand most people don't have a touchscreen

**Comment by Excigma** [comment]
I've dug around and found this: https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/538973868fbb04614c9d24988b9614e8f1c1081b/data/theme/gnome-shell-sass/widgets/_keyboard.scss

I've dug around on my system and found a folder: `/usr/local/share/themes/default-pure/gnome-shell` which has the transpiled css in it. [Apparently, this was generated by an app called GDM Settings](https://discourse.gnome.org/t/is-this-rendering-issue-already-filed/15379/8). Copying the relevant stuff from `/* On-screen Keyboard */` from the transpiled makes the keys visible.

![image](https://github.com/imarkoff/Marble-shell-theme/assets/30280397/86f6dce4-8c60-446d-8aa6-52aaa315f81c)


It also seems like it is possible to force the keyboard to show up without flipping my laptop with Settings > Accessibility > Typing > Screen keyboard (toggle on) and clicking on the search bar in Overview mode

**Comment by imarkoff** [comment]
Fixed. Buttons on the keyboard will change color when you hover over them, but I cannot guarantee that the buttons will change color when you tap them using a finger.

![image](https://github.com/imarkoff/Marble-shell-theme/assets/81307050/ffb23203-ff83-4e51-b9c7-92eb855922ed)
