### ISSUE TITLE
Displaced running dot on dash

### ISSUE THREAD

**Issue by user1-github** [imarkoff/Marble-shell-theme#27]
Hi,

Since Gnome 46.2 the running dot on dash is displaced (appears on top of the icon), but I see that your latest commit fixes the issue.

Is it possible to release an update with the fix?

Thanks in advance.

**Comment by imarkoff** [comment]
Sorry for the long delay in responding.

Here it is: https://github.com/imarkoff/Marble-shell-theme/releases/tag/46.2.3
