### ISSUE TITLE
Please add more contrast to the selected item in Alt-Tab and Super-Tab modes

### ISSUE THREAD

**Issue by ptsl** [imarkoff/Marble-shell-theme#29]
Hi,

I'm using the Marble theme in its yellow variant and I think it is one of the best Gnome shell themes around.
However, there is an issue with contrast. The selected item in the window selection (Alt-Tab) or application selection (Super-Tab, Super-`) modes is not visible enough. This is more pronounced on sunny days when some light reflections on the display are inevitable.

I'm afraid I cannot provide a screenshot as the key bindings don't allow me to interact with the screenshot tool. But I believe I have described the problem sufficiently.

Please, use a really contrasting color for the selected item.

Thank you for your work!
Peter

**Comment by imarkoff** [comment]
Hi! Thanks for issue. The selected item was really a bit hard to see, so now it looks like this

![image](https://github.com/imarkoff/Marble-shell-theme/assets/81307050/c59db4f6-edcb-46c4-8e42-dce6c76deedf)
![image](https://github.com/imarkoff/Marble-shell-theme/assets/81307050/92b917d6-4e07-434d-812e-6627305b556a)
