### ISSUE TITLE
feature request/suggestion: compact tweak

### ISSUE THREAD

**Issue by unlwly** [imarkoff/Marble-shell-theme#3]
smaller top bar/panel height (maybe 28-32px?), smaller sub menus (less padding) etc.
quick settings probably shouldn't be changed

would be pretty cool I think.

**Comment by imarkoff** [comment]
I went back to the standard panel height but idk if it looks normal. Looking forward to your feedback
Default height without button bg
![image](https://user-images.githubusercontent.com/81307050/225798433-f1110d86-aad3-4e10-89e5-730003b649e5.png)
Default height with button bg, default border radius
![image](https://user-images.githubusercontent.com/81307050/225798745-3715e338-ecbe-4799-94f8-fd80662172a5.png)
![image](https://user-images.githubusercontent.com/81307050/225799258-37ed89c6-197e-4e4a-8950-6efd0c2ff563.png)

Marble current style
![image](https://user-images.githubusercontent.com/81307050/225799103-4dd6f653-7959-4311-80c5-305e364d73f2.png)

**Comment by imarkoff** [comment]
> smaller top bar/panel height (maybe 28-32px?), smaller sub menus (less padding) etc. quick settings probably shouldn't be changed
> 
> would be pretty cool I think.

@unlwly, i went back to the standard panel height but idk if it looks normal. Looking forward to your feedback
Default height without button bg
![image](https://user-images.githubusercontent.com/81307050/225826036-d6dea9f0-2a55-48b0-b79e-f24d20c1c2a2.png)
Default height with button bg, default border radius
![image](https://user-images.githubusercontent.com/81307050/225826196-cb3b3f27-b992-4eff-a895-5221f6281ba4.png)
![image](https://user-images.githubusercontent.com/81307050/225826293-bb30e6e9-97cf-4cca-802e-18cb80821186.png)


Marble current style
![image](https://user-images.githubusercontent.com/81307050/225826340-3c36ade5-5a22-475f-9d39-168c682ddb05.png)

**Comment by unlwly** [comment]
default height LGTM

the no button bg would be great as a tweak, but that wouldn't be good for people who have blurred panels, unless they change the colour of the blur etc. so maybe a tweak on top of that to change text colour for the panel or something

**Comment by imarkoff** [comment]
> default height LGTM
> 
> the no button bg would be great as a tweak, 

Currently, in the 3-compact-tweak branch, you can use tweaks to resize the panel to the standard size or make the buttons background transparent. I'll add the ability to change the text color later. ik it looks super hard to write --def_panel_size, but i dunno how to shorten it.

>so maybe a tweak on top of that to change text colour for the panel or something

I'll add the ability to change the color of the text in a few days.
