### ISSUE TITLE
Failed to install GDM theme

### ISSUE THREAD

**Issue by anise0x7c** [imarkoff/Marble-shell-theme#30]
### Problem: Failed to install the GDM theme

- I'm sure that I had never installed another GDM theme because I was dong this on my newly installed Fedora 40.
- The theme was not installed on my mashine because the script said nothing to remove when I attempted to remove the theme afterwards
### Log:
```
anise@fedora:~$ pwd
/home/anise
```
```
anise@fedora:~$` cd Themes/Marble-shell-theme/`
```
```
anise@fedora:~/Themes/Marble-shell-theme$ sudo python install.py --gdm --blue
[sudo] anise 的密码：# sudo password #
Extracting gresource files...
/bin/sh: 行 1: gresource: 未找到命令  # /bin/sh: row 1: gresource: command no found #
Error: [Errno 2] No such file or directory: '.temp/gdm/theme/gnome-shell-light.css'
```
```
anise@fedora:~/Themes/Marble-shell-theme$ sudo python install.py --gdm -r
Theme is not installed. Nothing to remove.
If theme is still installed globally, try reinstalling gnome-shell package.
```
### System infomation:

- OS: Fedora Linux 40 (Workstation Edition) x86_64
- Shell: bash 5.2.26
- WM: Mutter (Wayland)
- WM Theme: Marble-blue-dark
- Theme: adw-gtk3-dark [GTK2/3/4]
- Icons: WhiteSur-dark [GTK2/3/4]
- Python Version: Python 3.12.4

**Comment by imarkoff** [comment]
> /bin/sh: 行 1: gresource: 未找到命令  # /bin/sh: row 1: gresource: command no found #

Install `glib2-devel` package
```
sudo dnf install glib2-devel
```

And try to install the theme again

**Comment by anise0x7c** [comment]
It works now thanks ;-)

**Comment by 0rd3p1** [comment]
I had the same problem on Debian 12.5, I tried to install libglib2.0-dev but it didn't work anyway

`pedro@desktop:~/Downloads/Marble-shell-theme$ sudo python3 install.py --gdm -a
Extracting gresource files...
Error: [Errno 2] No such file or directory: '.temp/gdm/theme/gnome-shell-light.css'
`
