### ISSUE TITLE
Custom hues default to yellow 

### ISSUE THREAD

**Issue by Cooploops77** [imarkoff/Marble-shell-theme#31]
Followed the instructions to create custom hues. I did hue 35 & 39 both resulted in the theme being the yellow theme when selecting hue 35 &39 in tweaks. Could be because they are similar In hue but was looking to make an orange theme. Do you have a fix or a recommended hue colour for this?

**Comment by imarkoff** [comment]
Try between `20` and `30`.

```
python install.py --hue=27 --name=orange --filled
```

![Screenshot from 2024-07-13 10-52-05](https://github.com/user-attachments/assets/d55c9cf1-0eb3-4b54-81d2-7000b93c9d19)
