### ISSUE TITLE
Add option to install theme without transparency effect 

### ISSUE THREAD

**Issue by mbeps** [imarkoff/Marble-shell-theme#35]
The theme has a slight transparency effect as shown below:

![image](https://github.com/user-attachments/assets/5abbc9a8-314b-4f28-b00f-e2f1594fee15)

It would be nice to have an option to not have this transparency and have it be opaque.

**Comment by imarkoff** [comment]
Now you can install the theme with `-O` or `--opaque` argument to make background in some places opaque
