### ISSUE TITLE
Make colors in colors.json editable

### ISSUE THREAD

**Issue by Humorist2601** [imarkoff/Marble-shell-theme#37]
Hello

Thank you for creating such a beautiful shell theme.

I wanted to know one thing, how should I go on about customizing the colors of this theme to match the catpuccin colors. I know I have to customize the colors.json but it has s,l,a only. The h is given by the user. Will the H remain constant throughout the color generation so that I can use some certain value i.e. 123.

Any help would he appreciated. Thank you :-)

**Comment by imarkoff** [comment]
Hi! Thanks for the question.

Yes, the script does not change hue throughout the color generation. It just converts hsla to rgba and replaces prepared values with the actual color.

**Comment by Humorist2601** [comment]
Is there anyway to assign the hue value inside the color.json file or the only way to use custom hue is through the scripts --hue option?

Thank You

**Comment by imarkoff** [comment]
Actually the script doesn't support custom colors in `colors.json`.
But you change the hue of the existing color (assign `123` to the - color `green`). Or you can try to add your own color (and even remove those you don't use) and install the theme with `-a` option.

**Comment by Humorist2601** [comment]
Wow I was not thinking that you will implement this. Love you brother. Thank you so much ❤️
