### ISSUE TITLE
The slider is not displayed correctly by gnome 47

### ISSUE THREAD

**Issue by radiolamp** [imarkoff/Marble-shell-theme#38]
![Без названия](https://github.com/user-attachments/assets/9bbaaac9-7a73-4df8-b8e9-95782bdbc668)

**Comment by NeformaliTu** [comment]
.toggle-switch { 
	background-image: url("./toggle-off.svg"); 
	/* size same as svg */
	height: 22px;  
	width: 38px; 
	background-color: rgba(216, 216, 216, 0.95); 
	border-radius: 99px; 
	box-shadow: inset 0 0 0 1px rgba(0, 0, 0, 0.05) !important; 
}
