### ISSUE TITLE
Light shell theme has problems suddenly.

### ISSUE THREAD

**Issue by khaled-0** [imarkoff/Marble-shell-theme#6]
I've tried clean installing all light themes but,
Sorry I don't remember exactly what updated last night, but everything was fine before that.
Probably gbome shell related

Showing weird icon colors on overview
![image](https://user-images.githubusercontent.com/74397286/235298819-6b16e658-3956-44c4-9f1a-18441f002114.png)

 Weird black bar on maximized windows
![image](https://user-images.githubusercontent.com/74397286/235298828-55a13e94-495f-48d0-b822-c32291c29a35.png)

Weird colors on quick actions sub menu
![image](https://user-images.githubusercontent.com/74397286/235298940-cb483edc-1d0e-4e63-a406-8c6c658babc8.png)

Same issue on screenshot panel too

None of those issues are present on Dark variant of the themes.
I'm using GNOME 44 Fedora 38
Thanks for making this beautiful theme

**Comment by khaled-0** [comment]
Apparently: Dark theme have that black border too.
But dark mode has overall less issues

**Comment by imarkoff** [comment]
With [this](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/beb77f58243265a6cc62b720a5b0ecd66efd50a1) commit, GNOME Shell has overrides in some places. That's why this bug appeared. So I will fix it in a while. 🐞
