### ISSUE TITLE
I tweaked it a bit to get an overview icon in the dash.

### ISSUE THREAD

**Issue by nkcong206** [imarkoff/Marble-shell-theme#8]
I took some code from another theme to add.

icon:
![launchpad](https://github.com/imarkoff/Marble-shell-theme/assets/56025592/e88cfff7-3dcd-4fbe-b50a-88edfd438509)

```
.show-apps .show-apps-icon {
  color: transparent !important;
  background-image: url("launchpad.png");
  background-size: contain;
}

.show-apps .overview-icon, .show-apps .show-apps-icon {
  color: transparent !important;
}

.show-apps .overview-icon {
	color: rgba(234, 243, 251, 1);
}
``` 
Result:
![Screenshot from 2023-05-28 11-54-54](https://github.com/imarkoff/Marble-shell-theme/assets/56025592/8609ecd6-257e-4fdd-aada-22d2636e8cfa)

**Comment by imarkoff** [comment]
I've added the ability to change the icon using tweaks:
```bash
python install.py ... --launchpad
```

Thank you for making this theme better. ❤️
